/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.models;


import com.revolut.task.models.tables.Account;
import com.revolut.task.models.tables.Currency;
import com.revolut.task.models.tables.Transactions;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = com.revolut.task.models.tables.Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.CURRENCY</code>.
     */
    public static final Currency CURRENCY = com.revolut.task.models.tables.Currency.CURRENCY;

    /**
     * The table <code>PUBLIC.TRANSACTIONS</code>.
     */
    public static final Transactions TRANSACTIONS = com.revolut.task.models.tables.Transactions.TRANSACTIONS;
}
