/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.models.tables;


import com.revolut.task.models.Indexes;
import com.revolut.task.models.Keys;
import com.revolut.task.models.Public;
import com.revolut.task.models.tables.records.CurrencyRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Currency extends TableImpl<CurrencyRecord> {

    private static final long serialVersionUID = 1008522255;

    /**
     * The reference instance of <code>PUBLIC.CURRENCY</code>
     */
    public static final Currency CURRENCY = new Currency();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CurrencyRecord> getRecordType() {
        return CurrencyRecord.class;
    }

    /**
     * The column <code>PUBLIC.CURRENCY.ID</code>.
     */
    public final TableField<CurrencyRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.CURRENCY.CODE</code>.
     */
    public final TableField<CurrencyRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CURRENCY.NAME</code>.
     */
    public final TableField<CurrencyRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CURRENCY.FACTOR</code>.
     */
    public final TableField<CurrencyRecord, BigDecimal> FACTOR = createField("FACTOR", org.jooq.impl.SQLDataType.DECIMAL.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>PUBLIC.CURRENCY.SYMBOL</code>.
     */
    public final TableField<CurrencyRecord, String> SYMBOL = createField("SYMBOL", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CURRENCY.CREATED_ON</code>.
     */
    public final TableField<CurrencyRecord, LocalDateTime> CREATED_ON = createField("CREATED_ON", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.CURRENCY.UPDATED_ON</code>.
     */
    public final TableField<CurrencyRecord, LocalDateTime> UPDATED_ON = createField("UPDATED_ON", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>PUBLIC.CURRENCY</code> table reference
     */
    public Currency() {
        this(DSL.name("CURRENCY"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CURRENCY</code> table reference
     */
    public Currency(String alias) {
        this(DSL.name(alias), CURRENCY);
    }

    /**
     * Create an aliased <code>PUBLIC.CURRENCY</code> table reference
     */
    public Currency(Name alias) {
        this(alias, CURRENCY);
    }

    private Currency(Name alias, Table<CurrencyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Currency(Name alias, Table<CurrencyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Currency(Table<O> child, ForeignKey<O, CurrencyRecord> key) {
        super(child, key, CURRENCY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_5, Indexes.PRIMARY_KEY_5);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CurrencyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CurrencyRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CurrencyRecord>> getKeys() {
        return Arrays.<UniqueKey<CurrencyRecord>>asList(Keys.CONSTRAINT_5, Keys.CONSTRAINT_50);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Currency as(String alias) {
        return new Currency(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Currency as(Name alias) {
        return new Currency(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Currency rename(String name) {
        return new Currency(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Currency rename(Name name) {
        return new Currency(name, null);
    }
}
