/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.models.tables.daos;


import com.revolut.task.models.tables.Currency;
import com.revolut.task.models.tables.records.CurrencyRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrencyDao extends DAOImpl<CurrencyRecord, com.revolut.task.models.tables.pojos.Currency, Integer> {

    /**
     * Create a new CurrencyDao without any configuration
     */
    public CurrencyDao() {
        super(Currency.CURRENCY, com.revolut.task.models.tables.pojos.Currency.class);
    }

    /**
     * Create a new CurrencyDao with an attached configuration
     */
    public CurrencyDao(Configuration configuration) {
        super(Currency.CURRENCY, com.revolut.task.models.tables.pojos.Currency.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.revolut.task.models.tables.pojos.Currency object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Currency> fetchById(Integer... values) {
        return fetch(Currency.CURRENCY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.revolut.task.models.tables.pojos.Currency fetchOneById(Integer value) {
        return fetchOne(Currency.CURRENCY.ID, value);
    }

    /**
     * Fetch records that have <code>CODE IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Currency> fetchByCode(String... values) {
        return fetch(Currency.CURRENCY.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>CODE = value</code>
     */
    public com.revolut.task.models.tables.pojos.Currency fetchOneByCode(String value) {
        return fetchOne(Currency.CURRENCY.CODE, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Currency> fetchByName(String... values) {
        return fetch(Currency.CURRENCY.NAME, values);
    }

    /**
     * Fetch records that have <code>FACTOR IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Currency> fetchByFactor(BigDecimal... values) {
        return fetch(Currency.CURRENCY.FACTOR, values);
    }

    /**
     * Fetch records that have <code>SYMBOL IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Currency> fetchBySymbol(String... values) {
        return fetch(Currency.CURRENCY.SYMBOL, values);
    }

    /**
     * Fetch records that have <code>CREATED_ON IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Currency> fetchByCreatedOn(LocalDateTime... values) {
        return fetch(Currency.CURRENCY.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>UPDATED_ON IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Currency> fetchByUpdatedOn(LocalDateTime... values) {
        return fetch(Currency.CURRENCY.UPDATED_ON, values);
    }
}
