/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.models.tables.daos;


import com.revolut.task.models.tables.Transactions;
import com.revolut.task.models.tables.records.TransactionsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionsDao extends DAOImpl<TransactionsRecord, com.revolut.task.models.tables.pojos.Transactions, Integer> {

    /**
     * Create a new TransactionsDao without any configuration
     */
    public TransactionsDao() {
        super(Transactions.TRANSACTIONS, com.revolut.task.models.tables.pojos.Transactions.class);
    }

    /**
     * Create a new TransactionsDao with an attached configuration
     */
    public TransactionsDao(Configuration configuration) {
        super(Transactions.TRANSACTIONS, com.revolut.task.models.tables.pojos.Transactions.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.revolut.task.models.tables.pojos.Transactions object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Transactions> fetchById(Integer... values) {
        return fetch(Transactions.TRANSACTIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.revolut.task.models.tables.pojos.Transactions fetchOneById(Integer value) {
        return fetchOne(Transactions.TRANSACTIONS.ID, value);
    }

    /**
     * Fetch records that have <code>FROM_ACCOUNT IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Transactions> fetchByFromAccount(Integer... values) {
        return fetch(Transactions.TRANSACTIONS.FROM_ACCOUNT, values);
    }

    /**
     * Fetch records that have <code>TO_ACCOUNT IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Transactions> fetchByToAccount(Integer... values) {
        return fetch(Transactions.TRANSACTIONS.TO_ACCOUNT, values);
    }

    /**
     * Fetch records that have <code>CURRENCY IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Transactions> fetchByCurrency(String... values) {
        return fetch(Transactions.TRANSACTIONS.CURRENCY, values);
    }

    /**
     * Fetch records that have <code>AMOUNT IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Transactions> fetchByAmount(BigDecimal... values) {
        return fetch(Transactions.TRANSACTIONS.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>CONVERTED_AMOUNT IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Transactions> fetchByConvertedAmount(BigDecimal... values) {
        return fetch(Transactions.TRANSACTIONS.CONVERTED_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>CREATED_ON IN (values)</code>
     */
    public List<com.revolut.task.models.tables.pojos.Transactions> fetchByCreatedOn(LocalDateTime... values) {
        return fetch(Transactions.TRANSACTIONS.CREATED_ON, values);
    }
}
