/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.models.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 1125730954;

    private final Integer       id;
    private final String        name;
    private final BigDecimal    balance;
    private final Boolean       active;
    private final String        currencyCode;
    private final LocalDateTime createdOn;
    private final LocalDateTime updatedOn;

    public Account(Account value) {
        this.id = value.id;
        this.name = value.name;
        this.balance = value.balance;
        this.active = value.active;
        this.currencyCode = value.currencyCode;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Account(
        Integer       id,
        String        name,
        BigDecimal    balance,
        Boolean       active,
        String        currencyCode,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.name = name;
        this.balance = balance;
        this.active = active;
        this.currencyCode = currencyCode;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public Boolean getActive() {
        return this.active;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(balance);
        sb.append(", ").append(active);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
