/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.models.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Currency implements Serializable {

    private static final long serialVersionUID = 611376161;

    private final Integer       id;
    private final String        code;
    private final String        name;
    private final BigDecimal    factor;
    private final String        symbol;
    private final LocalDateTime createdOn;
    private final LocalDateTime updatedOn;

    public Currency(Currency value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.factor = value.factor;
        this.symbol = value.symbol;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    public Currency(
        Integer       id,
        String        code,
        String        name,
        BigDecimal    factor,
        String        symbol,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.factor = factor;
        this.symbol = symbol;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public String getCode() {
        return this.code;
    }

    public String getName() {
        return this.name;
    }

    public BigDecimal getFactor() {
        return this.factor;
    }

    public String getSymbol() {
        return this.symbol;
    }

    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Currency (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(factor);
        sb.append(", ").append(symbol);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
