/*
 * This file is generated by jOOQ.
 */
package com.revolut.task.models.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transactions implements Serializable {

    private static final long serialVersionUID = -1056254745;

    private final Integer       id;
    private final Integer       fromAccount;
    private final Integer       toAccount;
    private final String        currency;
    private final BigDecimal    amount;
    private final BigDecimal    convertedAmount;
    private final LocalDateTime createdOn;

    public Transactions(Transactions value) {
        this.id = value.id;
        this.fromAccount = value.fromAccount;
        this.toAccount = value.toAccount;
        this.currency = value.currency;
        this.amount = value.amount;
        this.convertedAmount = value.convertedAmount;
        this.createdOn = value.createdOn;
    }

    public Transactions(
        Integer       id,
        Integer       fromAccount,
        Integer       toAccount,
        String        currency,
        BigDecimal    amount,
        BigDecimal    convertedAmount,
        LocalDateTime createdOn
    ) {
        this.id = id;
        this.fromAccount = fromAccount;
        this.toAccount = toAccount;
        this.currency = currency;
        this.amount = amount;
        this.convertedAmount = convertedAmount;
        this.createdOn = createdOn;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getFromAccount() {
        return this.fromAccount;
    }

    public Integer getToAccount() {
        return this.toAccount;
    }

    public String getCurrency() {
        return this.currency;
    }

    public BigDecimal getAmount() {
        return this.amount;
    }

    public BigDecimal getConvertedAmount() {
        return this.convertedAmount;
    }

    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transactions (");

        sb.append(id);
        sb.append(", ").append(fromAccount);
        sb.append(", ").append(toAccount);
        sb.append(", ").append(currency);
        sb.append(", ").append(amount);
        sb.append(", ").append(convertedAmount);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
}
